development:
  adapter: postgresql
  encoding: unicode
  database: gid_development
  pool: 5
  username: postgres
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: gid_test
  pool: 5
  username: postgres
  password:
  host: localhost
